name: CI Básico Java

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    steps:
    - name: Obtener código
      uses: actions/checkout@v3

    - name: Configurar Java 21
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21

    - name: Compilar prueba de humo
      run: |
        mkdir -p target
        javac -d target src/test/PruebaTravis.java

    - name: Ejecutar prueba de humo
      run: java -cp target PruebaTravis
